"""configured comments limits

Revision ID: 0677a52c813c
Revises: 8a776413a419
Create Date: 2026-04-11 12:39:16.915199

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


revision: str = '0677a52c813c'
down_revision: Union[str, None] = '8a776413a419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
