"""published_at for publications

Revision ID: 8a776413a419
Revises: 080164b1aa7c
Create Date: 2026-04-10 17:26:42.053246

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


revision: str = '8a776413a419'
down_revision: Union[str, None] = '080164b1aa7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE publications SET published_at = created_at")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'published_at')
    # ### end Alembic commands ###
